spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: lb://TEST
          predicates:
            - Path=/api/v1/test/**

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.3:8761/eureka
  instance:
    prefer-ip-address: true
