spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank?serverTimezone=Asia/Seoul
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


jwt:
  secret: asdfaerrwesdfserw2asdfaerrwesdfserw2321
  expiration: 86400000