spring:
  application:
    name: spring-db
  datasource:
    url: jdbc:mysql://localhost:3306/data1?serverTimezone=Asia/Seoul
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
#      create = drop -> create
#    create-drop = drop -> create -> drop
#    update = create -> alter
#    none = x
    show-sql: true